# Iterations

## For Loops

### Across ranges

In [1]:
print("From 0 to 10 with step=2")
for i in range(0,10,2):
    print(i)

From 0 to 10 with step=2
0
2
4
6
8


In [4]:
import numpy as np
print("Range of 5 elements from 0 to 10")
for i in np.linspace(0,10,5):
    print(i)

Range of 5 elements from 0 to 10
0.0
2.5
5.0
7.5
10.0


Very usefull to create indexes and access the elements of lists by their position

In [3]:
vector=[2,4,6,8,10]
for i in range(len(vector)):
    print("Element {}: {}".format(i,vector[i]))

Element 0: 2
Element 1: 4
Element 2: 6
Element 3: 8
Element 4: 10


### Across lists

Directly without using indexes

In [4]:
prod=1
for i in [1,2,3,4,5,6]:
    prod = prod*i
    print(prod)

1
2
6
24
120
720


### Across strings

Directly without using indexes

In [5]:
for letter in "Kinesiotherapy":
    print(letter,end='_')

K_i_n_e_s_i_o_t_h_e_r_a_p_y_

Or with Indexes

In [1]:
word="Kinesiotherapy"
for index in range(len(word)):
    print(word[index],end='_')

K_i_n_e_s_i_o_t_h_e_r_a_p_y_

### Across list of tuples

accessing directly the elements of the tuple with two variables

In [6]:
list_of_tuples=[("uno",1),("dos",2),("tres",3),("cuatro",4),("cinco",5)]
for k,v in list_of_tuples:
    print(k," is ",v)

uno  is  1
dos  is  2
tres  is  3
cuatro  is  4
cinco  is  5


### Across dictionaries

accessing directly the key and the value with two variables

In [7]:
dictionary={"Teo":"admin","Liam":"viewer","Dora":"root","Noa":"viewer","Cris":"Viewer"}

for k,v in dictionary.items():
    print(k," has the rol of ",v)

Teo  has the rol of  admin
Liam  has the rol of  viewer
Dora  has the rol of  root
Noa  has the rol of  viewer
Cris  has the rol of  Viewer


In [8]:
for k in dictionary.keys():
    print("Key: ",k)
    
for v in dictionary.values():
    print("Value: ",v)

Key:  Teo
Key:  Liam
Key:  Dora
Key:  Noa
Key:  Cris
Value:  admin
Value:  viewer
Value:  root
Value:  viewer
Value:  Viewer


### Nested loops

In [10]:
import numpy as np
array = np.array([(1,2,3),(4,5,6),(6,7,8)])
print(array)
print("Numpy arrays can be accessed as A[row,col]")
rows,cols=array.shape

for r in range(rows):
    for c in range(cols):
        print("Array element [{},{}]".format(r,c)," value: ",array[r,c])

[[1 2 3]
 [4 5 6]
 [6 7 8]]
Numpy arrays can be accessed as A[row,col]
Array element [0,0]  value:  1
Array element [0,1]  value:  2
Array element [0,2]  value:  3
Array element [1,0]  value:  4
Array element [1,1]  value:  5
Array element [1,2]  value:  6
Array element [2,0]  value:  6
Array element [2,1]  value:  7
Array element [2,2]  value:  8


### For loops with BREAK

In [11]:
for n in range(2, 20):
    for x in range(2, n):
        if n % x == 0:
            print(n, 'equals', x, '*', n/x)
            break

4 equals 2 * 2.0
6 equals 2 * 3.0
8 equals 2 * 4.0
9 equals 3 * 3.0
10 equals 2 * 5.0
12 equals 2 * 6.0
14 equals 2 * 7.0
15 equals 3 * 5.0
16 equals 2 * 8.0
18 equals 2 * 9.0


## WHILE loops

### Simple loops

In [13]:
stay=True
while stay==True:
    command=input("Write exit to abort: ")
    if command=="exit": stay=False
print("EXIT!")

Write exit to abort: exit
EXIT!


### While on strings

**¡¡¡¡Runnig this cell will need to restart the Kernel!!!**

Because it implements an infinite loop

In [ ]:
x= "Kinesiotherapy"
while x:
    print(x)

Running this cell is safe.

Note the differences

In [14]:
x= "Kinesiotherapy"
while x:
    print(x)
    x=x[1:]

Kinesiotherapy
inesiotherapy
nesiotherapy
esiotherapy
siotherapy
iotherapy
otherapy
therapy
herapy
erapy
rapy
apy
py
y


### While with comparision operators

In [2]:
stocks = 1000
stock_price = 10
losts = 0
threshold = 1000

print("I payed ",stocks*stock_price, "€ to buy ", stocks, " stocks")
print("I accept to lose 1000€ maximum")

I payed  10000 € to buy  1000  stocks
I accept to lose 1000€ maximum


In [5]:
while losts < threshold:
    new_price = np.random.normal(10, 1, 1)[0]
    print("New day, stock price: ",new_price)
    losts = 10000 - stocks*new_price
    if losts >=0: 
        print("Losts: ",losts)
    else: 
        print("Gains: ",-losts)
    

New day, stock price:  9.459547752648902
Losts:  540.4522473510988
New day, stock price:  10.753749015993716
Gains:  753.7490159937151
New day, stock price:  11.130243561234616
Gains:  1130.2435612346162
New day, stock price:  10.621679563207985
Gains:  621.6795632079848
New day, stock price:  10.075283176627025
Gains:  75.28317662702466
New day, stock price:  11.59134387150141
Gains:  1591.343871501409
New day, stock price:  11.288471119832497
Gains:  1288.4711198324967
New day, stock price:  8.965998836007813
Losts:  1034.0011639921868


### While loops with break, continue

This code will find the largest factor for a number "y". If no factor is found, then it means its a prime number

In [7]:
y=198
x = y-1
while x > 1:
    if y % x == 0:                   
        print(y, 'has factor', x)
        break
    x -= 1
if x==1:
    print(y, 'is prime')

199 is prime


This code finds even numbers. 

If the number iterated is odd, then the "continue" statements returns to the head of the block without printing

In [18]:
x = 1
while x:
    x=x+1                     
    if x % 2 != 0: continue
    print(x, end=' ')
    if x == 100: break

2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98 100 

Many loops can be implemented also with for statement

In [19]:
for x in range(1,100,1):              
    if x % 2 != 0: continue
    print(x, end=' ')

2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98 

## List Comprehensions

### Easy examples

In [21]:
[x.upper() for x in "change case"]

['C', 'H', 'A', 'N', 'G', 'E', ' ', 'C', 'A', 'S', 'E']

In [22]:
[x.upper() for x in "n0w w1th numb3rs" if x.islower()]

['N', 'W', 'W', 'T', 'H', 'N', 'U', 'M', 'B', 'R', 'S']

In [23]:
sequence=[0,1,2,3,4,5,6,7,8,9,10]

["Even: "+str(x) for x in sequence if x%2==0]

['Even: 0', 'Even: 2', 'Even: 4', 'Even: 6', 'Even: 8', 'Even: 10']

#### Be aware that a list is always returned, even if it's empty

In [24]:
sequence=[0,1,2,3,4,5,6,7,8,9,10]

[print("Even: "+str(x)) for x in sequence if x%2==0]

Even: 0
Even: 2
Even: 4
Even: 6
Even: 8
Even: 10


[None, None, None, None, None, None]

#### Tuples and dictionaries are also collections to be used with list comprehensions

In [25]:
sequence=('blowfish', 'clownfish', 'catfish', 'octopus')

[x.upper() for x in sequence if "fish" in x]

['BLOWFISH', 'CLOWNFISH', 'CATFISH']

In [26]:
dictionary={"Hola":"spanish","Bonjour":"french","Hello":"english",
            "Adios":"spanish","Au revoir":"french","Bye":"english"}

[k for k,v in dictionary.items() if v=="spanish" ]

['Hola', 'Adios']

### Medium examples

#### Nested For Loops

In [27]:
my_list = []

for x in [20, 40, 60]:
    for y in [2, 4, 6]:
        my_list.append(x * y)

print(my_list)

[40, 80, 120, 80, 160, 240, 120, 240, 360]


In [28]:
my_list = [x * y for x in [20, 40, 60] for y in [2, 4, 6]]
my_list

[40, 80, 120, 80, 160, 240, 120, 240, 360]

#### Flat map list of list

In [29]:
list_of_list=[[1, 2, 3], [4, 5, 6], [7], [8, 9]]

flat_list = []
for sublist in list_of_list:
    for item in sublist:
        flat_list.append(item)
        
flat_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [30]:
flat_list = [item for sublist in list_of_list for item in sublist]
flat_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

#### Nested If

In [31]:
number_list=[]
for x in range(100):
    if x % 3 == 0 :
        if x % 5 == 0 :
            number_list.append(x)
print("List of 3 and 5 multiples")
print(number_list)

List of 3 and 5 multiples
[0, 15, 30, 45, 60, 75, 90]


In [32]:
number_list = [x for x in range(100) if x % 3 == 0 and x % 5 == 0]
print("List of 3 and 5 multiples")
print(number_list)

List of 3 and 5 multiples
[0, 15, 30, 45, 60, 75, 90]


### Hard examples

#### Create a diagonal matrix

In [33]:
matrix=[[0,0,0],[0,0,0],[0,0,0]]
for row_idx in range(0, 3):
    for item_idx in range(0, 3):
        if item_idx == row_idx :
            matrix[row_idx][item_idx]=1
        else:
            matrix[row_idx][item_idx]=0

matrix

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]

In [34]:
[ [ 1 if item_idx == row_idx else 0 for item_idx in range(0, 3) ] for row_idx in range(0, 3) ]

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]